# Use official Node.js LTS image
FROM node:16-alpine

# Create app directory
WORKDIR /usr/src/app

# Copy package files first for better caching
COPY package*.json ./

# Install dependencies
RUN npm install --production

# Copy the rest of the application
COPY . .

# Expose the port your app runs on
EXPOSE 4000


# Start the application
CMD ["npm", "run", "dev"]

